#!/bin/sh
#
# File: $HOME/.xsession
#  - Executed by xdm/gdm/sddm at login

nm-applet --sm-disable &
bluedevil-monolithic
#blueman-applet &
gensig -q
owncloud &
xss-lock -- /usr/bin/i3lock --color=222222 -n &
konsole &
xinput disable "SynPS/2 Synaptics TouchPad"
exec $@
