#!/bin/sh
#
# File: $HOME/.xsession
#  - Executed by xdm/gdm/kdm at login

#. $HOME/.xprofile
exec /usr/bin/gpg-agent --enable-ssh-support --daemon $HOME/.run-wm
#exec /usr/bin/ck-launch-session /usr/bin/gpg-agent --enable-ssh-support --daemon $HOME/.run-wm
